<div class="user-infor"></div>
<div class="MenuMobie d-flex Mobie hidden-lg hidden-md">
    <a href="#/don-hang" class="text-center" >
        <div class="btn btn-mobie">
            <img class="img img-responsive" src="/public/AppMobie/Icon/order.png" >
        </div>
        <br>
        <span>Đơn Hàng</span>
    </a>
    <a href="#/lich-su" class="text-center" >
        <div class="btn btn-mobie">
            <img class=" img img-responsive" src="/public/AppMobie/timeline.png" >
        </div>
        <br>
        <span>Lịch Sử ĐH</span>
    </a>
    <a href="#/qrcode" class="text-center" >
        <div class="btn btn-mobie">
            <img class=" img img-responsive" src="/public/AppMobie/qr-code-1851030-1569017.png" >
        </div>
        <br>
        <span>Quét Mã</span>
    </a>
</div>
<footer-mobie class="hidden-lg hidden-md" ></footer-mobie>
<div class="hidden-sm hidden-xs dashboard-desktop ">

</div>

