<back-to-home title="Danh Sách Đơn Hàng" ></back-to-home>
<div class="body-content Donhangs" ng-init="DanhSachDonHang(_Params, 1, 10)" >
    <div class="btn-mobie-top-right pull-right dropdown"  style="margin-top: -7px;">
        <div class="d-flex">
            <label class="btn" style="display: block;color: #000;" >
                <i class="fa-2x fa fa-search"  ></i>
                <input style="display: none;" type="checkbox" ng-model="showtimkiem"  >
            </label>
            <div class="pull-right hidden dropdown btn"  style="width: 50%;">
                <button  style="line-height: 20px;color: #000;" class="dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa-2x fa fa-ellipsis-v"  ></i>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                    <li>

                        <label style="display: block;color: #000;padding: 10px;" >
                            <i class="fa fa-list" ></i>
                            <input style="display: none;" type="checkbox" ng-model="showtimkiem"  >
                            Tìm kiếm
                        </label>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <div class="d-flex" ng-show="showtimkiem" >
        <input ng-change='DanhSachDonHang(_DanhSachDonHang.params, 1, 10)' ng-model="_DanhSachDonHang.params.Keyword" placeholder="Tìm Kiếm"  class="form-control" >
        <button class="btn border-radius-none btn-primary" ><i class="fa fa-search" ></i></button>
    </div>
    <ul class="list-group" style="margin-bottom: 0px;" >
        <li class="list-group-item" ng-repeat="item in _DanhSachDonHang.data" >
            <a href="#/don-hang/{{item.CodeOrder}}">
                <b>#{{$index + 1 + (_DanhSachDonHang.pagesIndex - 1) * _DanhSachDonHang.pagesNumber}}</b>
                <i style="margin-top: -6px;" class="pull-right fa fa-angle-right fa-2x" ></i>
                Khách hàng:  <b>{{item.Name}}</b>
                <br>
                <b class="color-red" ng-bind-html="'Tổng Đơn: ' +item.TotalPriceVND" ></b>
                <span class="pull-right" >{{item.statusName}}</span>
            </a>
        </li>
    </ul>
    <phan-trang1 pages-index="_DanhSachDonHang.pagesIndex"
                 pages-number="_DanhSachDonHang.pagesNumber"
                 pages-total="_DanhSachDonHang.pagesTotal"
                 pages-link=""
                 pages-params='_DanhSachDonHang.params'
                 on-click="DanhSachDonHang(Params, pagesIndex, pagesNumber)"></phan-trang1>
</div>
<footer-mobie></footer-mobie>