<div class=" MobieFooter hidden-md hidden-lg" >
    <a href="/" class="" >
        <div class="btn btn-mobie">
            <img src="/public/AppMobie/Icon/Home.png" alt="home"/>
        </div>
        <br>
        <span>Trang Chủ</span>
    </a>
    <a href="/cart/" class="" >
        <div  class="btn btn-mobie">
            <label style="" >{{_Cart.SumProduct}}</label>
            <img src="/public/AppMobie/Cart.png" alt="qrcode"/>
        </div>
        <br>
        <span>Giỏ Hàng</span>
    </a>
    <a href="#/qrcode" class="" >
        <div class="btn btn-mobie">
            <img src="/public/AppMobie/qr-code-1851030-1569017.png" alt="qrcode"/>
        </div>
        <br>
        <span>QRCode</span>
    </a>
    <a href="#/thongbao" class="" >
        <div class="btn btn-mobie">
            <img class="img img-responsive" src="/public/AppMobie/timeline.png" alt="timeline"/>
        </div>
        <br>
        <span>Thông báo</span>
    </a>
    <a href="#/thongtin" class="" >
        <div class="btn btn-mobie">
            <img class="img img-responsive" src="/public/AppMobie/Icon/User.png" alt="timeline"/>
        </div>
        <br>
        <span>Tài Khoản</span>
    </a>
</div>