<back-to-home title="Quét Mã" ></back-to-home>
<div class="class" ng-init="GetCamera()" >

    <div class="box box-primary">
        <div class="box-body">
            <video poster="/public/camera_loading.svg?v=<?php echo time(); ?>" style="width: 100%;margin: auto; max-height: 500px;" id="preview">
                loadvideo
            </video>
        </div>
        <div class="box-footer text-center">
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-primary active">
                    <input type="radio" name="options" value="0" autocomplete="off" checked> Camera 1
                </label>
                <label class="btn btn-primary ">
                    <input type="radio" name="options" value="1" autocomplete="off" checked> Camera 2
                </label>
                <label class="btn btn-primary">
                    <input type="radio" name="options" value="2" autocomplete="off"> Camera 3
                </label>
            </div>
        </div>
    </div>
    <div id="Camera" class=""></div>
    <div class="thongbao bg-green" id="alertCode"></div>
    <div class="clearfix" ></div>
</div>

<footer-mobie></footer-mobie>