<div class="container-fluid">
    <form method="get" action="">
        <div class="form-group d-flex">
        </div>
    </form>
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Danh sách khoa </h3>
            <div class="box-tools">
                <a href="/options/post/<?php echo $params["GroupsId"]; ?>/" class="btn btn-primary"><i class="fa fa-plus"></i></a>
            </div>
        </div>
        <div class="box-body">
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th>STT</th>
                        <th>Mã </th>
                        <th>Tên</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if ($Items) {
                        foreach ($Items as $k => $item) {
                            $_item = new Model_OptionsService($item);
                    ?>
                            <tr>
                                <th>
                                    <a class="btn btn-sm btn-primary" href="/options/put/<?php echo $_item->Id ?>">Sửa</a>
                                    <a onclick="return confirm('Xoá khoa này?')" class="btn btn-sm btn-danger" href="/options/delete/<?php echo $_item->Id ?>">Xoá</a>
                                </th>
                                <th><?php echo $k + 1 ?></th>
                                <th><?php echo $_item->Val ?></th>
                                <th><?php echo $_item->Name ?></th>
                            </tr>
                    <?php
                        }
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</div>