 <div class="container">
    <form action="" enctype="multipart/form-data" method="POST" >
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Thêm</h3>
                <div class="box-tools">
                    <!--<a href="#" class="btn btn-primary" ><i class="fa fa-plus" ></i></a>-->
                </div>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Mã</label>
                            <input required="" type="text" class="form-control" name="op[Val]" >
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Tên</label>
                            <input required="" type="text" class="form-control" name="op[Name]" >
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="">Mô Tả</label>
                    <textarea type="text" class="form-control" name="op[Des]" ></textarea>
                </div>
                <div class="form-group hidden">
                    <label for="">Nhóm</label>
                    <input type="text" readonly="" class="form-control" value="<?php echo $_Param[0]; ?>" name="op[GroupsId]" >
                </div> 
            </div>
            <div class="box-footer">
                <button class="btn btn-success" >Lưu</button>
            </div>
        </div>

    </form>
</div>
