<div class="page-content checkout-page">
    <div class="box-border mb-2">
        <div class="row">
            <div class="col-sm-12">
                <label for="email_address_1" class="required">SĐT <span style="color: red;" >(*)</span></label>
                <div class="d-flex" >
                    <input class="input form-control" ng-change="TimThongTinKhachHangTheoSDT(Order.Phone)" required="required" type="text" ng-model="Order.Phone" name="SDT" id="SDTInput">
                    <button type="button" class="btn btn-success"  ng-click="TimThongTinKhachHangTheoSDT(Order.Phone)" ><i class="fa fa-search" ></i></button>
                </div>
            </div><!--/ [col] -->
            <div class="col-sm-6">
                <label for="first_name_1" class="required">Họ Tên <span style="color: red;" >(*)</span></label>
                <input class="input form-control" required="required" type="text" ng-model="Order.Name" name="Name" id="NameInput">
            </div><!--/ [col] -->
            <div class="col-sm-6">
                <label for="email_address_1" >Email</label>
                <input class="input form-control"  ng-model="Order.Email" type="email" name="Email"  id="EmailInput">
            </div>
            <div>
                <div class="col-sm-6">
                    <label  class="required">Tỉnh/Thành Phố</label>
                    <select class="form-control"  ng-model="_Tinh" name="Tinh" >
                        <option ng-repeat="item in _TinhThanh" value="{{item.Id}}" >{{item.Name}}</option>
                    </select>
                </div><!--/ [col] -->
                <div class="col-sm-6">
                    <label class="required">Quận/Huyện</label>
                    <select class="form-control" ng-model="_Huyen" name="Huyen" >  ;
                        <option ng-repeat="item in _QuanHuyen" value="{{item.Id}}" >{{item.Name}}</option>
                    </select>
                </div><!--/ [col] -->
                <div class="col-xs-12">
                    <label for="address_1" class="required">Số Nhà, Đường</label>
                    <input class="input form-control" type="text" ng-model="Order.Duong" name="Duong" id="address_1">
                </div>
            </div>
        </div>
    </div>
</div>