<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Trang đặt hàng thất bại</h3>
    </div>
    <div class="box-body">
        <form action="" enctype="multipart/form-data" method="POST">
            <div class="form-group">
                <textarea type="text" class="editor" id="DatHangThatBai" name="DatHangThatBai"><?php echo $data["ContentPage"] ?></textarea>
            </div>
            <button class="btn btn-success">Lưu</button>
        </form>
    </div>
</div>