<?php
$functionLayout = new theme\home\functionLayout();
?>
<!DOCTYPE html>
<html>
    <head>
        <?php
        $functionLayout->head();
        ?>

        <link href="/public/Profile/MobieApp.css?v=<?php echo filemtime('public/Profile/MobieApp.css'); ?>" rel="stylesheet" type="text/css"/>
        <script src="/public/Profile/Profile.js?v=<?php echo filemtime('public/Profile/Profile.js'); ?>" type="text/javascript"></script>
    </head>
    <body class="option5 cartPage" ng-cloak="TRUE" ng-app="rootApp" ng-controller="menuController" >
        <?php
        $functionLayout->header();
        ?>
        <div class="" ng-init="profileInit()" ng-controller="profileController" >
            <div class="container" id="columns"  >
                <?php
                $bre = new Model\Breadcrumb();
                $bre->showBreadcrumb();
                ?>
            </div>
            <?php
            include $Content;
            ?>
        </div>
        <?php
        $functionLayout->footer();
        $functionLayout->js();
        ?>
    </body>
</html>
<?php
$functionLayout->DeCodeHTML();
?>