<?php
$functionLayout = new theme\home\functionLayout();
?>
<!DOCTYPE html>
<html>
    <head>
        <?php
        $functionLayout->head();
        ?>
    </head>
    <body class="option5" ng-cloak="TRUE" ng-app="rootApp" ng-controller="menuController" >
        <?php
        $functionLayout->header();
        $functionLayout->homeslider();
        $functionLayout->services();
        include $Content;
        $functionLayout->footer();
        ?>
        <a href="#" class="scroll_top" title="Scroll to Top" style="display: inline;">Scroll</a>
        <?php
        $functionLayout->js();
        ?>
    </body>
</html>
<?php
$functionLayout->DeCodeHTML();
?>