<?php
$functionLayout = new theme\home\functionLayout();
?>
<!DOCTYPE html>
<html>
    <head>
        <?php
        $functionLayout->head();
        ?>
        <link href="/public/Profile/MobieApp.css?v=<?php echo filemtime('public/Profile/MobieApp.css'); ?>" rel="stylesheet" type="text/css"/>
        <script src="/public/Profile/Profile.js?v=<?php echo filemtime('public/Profile/Profile.js'); ?>" type="text/javascript"></script>
    </head>
    <body class="option5 homeUser" ng-cloak="TRUE" ng-app="rootApp" ng-controller="menuController" >
        <?php
        $functionLayout->header();
        ?>
        <div class="columns-container"  >
            <div class="container" id="columns">
                <?php
//                $bre = new Model\Breadcrumb();
//                $bre->showBreadcrumb();
                ?>
                <div class="hidden-sm hidden-xs left-menu column col-xs-12 col-sm-3" id="left_column">
                    <div class="block left-module">
                        <p class="title_block">Danh Mục Sản Phẩm</p>
                    </div>
                </div>
                <div class="center_column col-xs-12 col-sm-9" id="center_column">
                    <?php
                    include $Content;
                    ?>
                </div>
            </div>
        </div>
        <?php
        $functionLayout->footer();
        ?>
        <a href="#" class="scroll_top" title="Scroll to Top" style="display: inline;">Scroll</a>
        <?php
        $functionLayout->js();
        ?>
    </body>
</html>
<?php
$functionLayout->DeCodeHTML();
?>