<?php
$functionLayout = new theme\home\functionLayout();
?>
<!DOCTYPE html>
<html>

<head>
    <?php
    $functionLayout->head();
    ?>
    <link href="/public/Profile/MobieApp.css?v=<?php echo filemtime('public/Profile/MobieApp.css'); ?>" rel="stylesheet" type="text/css" />
    <script src="/public/Profile/Profile.js?v=<?php echo filemtime('public/Profile/Profile.js'); ?>" type="text/javascript"></script>
</head>

<body class="">
    <div class="">
        <?php
        include $Content;
        ?>
    </div>
    <?php
    $functionLayout->js();
    ?>
</body>

</html>
<?php
$functionLayout->DeCodeHTML();
?>