<?php
$Model_Duser = new Module\duser\Model\Duser();
$DSOption = $Model_Duser->Admins(FALSE);
?>
<div class="clearfix"></div>
<div class="box box-primary ">
    <div class="box-header">
        <h3 class="box-title">Danh Sách Tài Khoản
        </h3>
        <div class="box-tools">
            <a href="<?php echo \Module\duser\Model\LinkCommon::LinkAddUser() ?>" class="pull-right btn btn-primary">
                __langAdd___ <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    <div class="box-body">
        <table id="datatablea" class="dataTable table table-bordered table-hover ">
            <thead>
                <tr>
                    <th>Họ & Tên</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Nhóm</th>
                    <th>Sđt</th>
                    <th>Khoa</th>
                    <th>Ghi Chú</th>

                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($DSOption as $User) {
                    $_User = new \Module\duser\Model\Duser($User);
                ?>
                    <tr>
                        <td>
                            <a href="<?php echo Module\duser\Model\LinkCommon::LinkEdit($User["Username"]); ?>">
                                <?php echo $_User->Name; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo Module\duser\Model\LinkCommon::LinkEdit($User["Username"]); ?>">
                                <?php echo $User["Username"] ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo Module\duser\Model\LinkCommon::LinkEdit($User["Username"]); ?>">
                                <?php echo $User["Email"] ?>
                            </a>
                        </td>
                        <td><?php echo $_User->Groups(); ?></td>
                        <td>
                            <a href="<?php echo Module\duser\Model\LinkCommon::LinkEdit($User["Username"]); ?>">
                                <?php echo $User["Phone"] ?>
                            </a>
                        </td>
                        <td>
                            <?php
                            foreach ($_User->KhoaBenh() as $key => $value) {
                                echo "<label class='label label-primary' >{$value->Name}</label>";
                            }
                            ?>

                        </td>
                        <td><?php echo $User["Note"] ?></td>

                    </tr>
                <?php
                }
                ?>
            </tbody>
            <tfoot>
                <tr>
                    <th>Họ & Tên</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Nhóm</th>
                    <th>Sđt</th>
                    <th>Khoa</th>
                    <th>Ghi Chú</th>
                </tr>
            </tfoot>

        </table>
    </div>
</div>