<?php

use Module\duser\Model\FormUser;

$Model_Duser = new Module\duser\Model\Duser();
$DSOption = $Model_Duser->Admins(FALSE);
$User = new \Module\duser\Model\Duser($User);
$CurentUser = \Module\duser\Model\Duser::CurentUsernameAdmin(true);
if (\Module\duser\Model\Duser::KiemTraQuyen([
    \Module\duser\Model\Duser::admin,
    \Module\duser\Model\Duser::Superadmin
]) == FALSE) {
    die("Bạn không có Quyền.");
    header("Location: /duser/aprofile/index");
}
?>
<div class="" style="margin-top: 10px;" ng-controller="usersCotroller">
    <div class="col-md-6">
        <?php
        $Error = Model\Error::getAllError();
        if ($Error) {
        ?>
            <div class="col-sm-12">
                <div style="position: fixed;top: 100px;right: 0px;width: 300px;z-index: 1999" class="alert alert-<?php echo $Error["Type"] ?> alert-dismissible">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <?php echo $Error["Content"]; ?>
                </div>

            </div>
        <?php
        }
        ?>
        <form method="post" action="" enctype="multipart/form-data">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Sửa Tài Khoản</h3>
                </div>
                <div class="box-body">
                    <div class="form-group">
                        <label for="">Họ & Tên</label>
                        <input type="text" value="<?php echo $User->Name; ?>" class="form-control" name="user[Name]" placeholder="Họ & Tên">
                    </div>
                    <div class="form-group">
                        <label for="">Tài Khoản</label>
                        <input type="text" readonly="readonly" value="<?php echo $User->Username; ?>" class="form-control" name="user[Username]" placeholder="Tài Khoản">
                    </div>

                    <div class="form-group">
                        <label for="">Email</label>
                        <input type="email" value="<?php echo $User->Email; ?>" class="form-control" name="user[Email]" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="">SĐT</label>
                        <input type="text" value="<?php echo $User->Phone; ?>" class="form-control" name="user[Phone]" placeholder="SĐT">
                    </div>
                    <?php
                    FormUser::Groups($User->Groups)->renderHTML();
                    ?>
                    <div class="col-md-12">
                        <?php
                        FormUser::KhoaBenh($User->KhoaBenhVal())->renderHTML();
                        ?>
                    </div>
                    <?php
                    FormUser::Address($User->Address)->renderHTML();
                    FormUser::Note($User->Note)->renderHTML();
                    ?>
                    <div class="form-group">
                        <label for=""></label>
                        <?php
                        if ($User->Groups > -1) {
                        ?>
                            <input type="submit" class="btn btn-success" name="SaveAdmin" value="Lưu Thông Tin">

                        <?php
                        }
                        ?>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <?php
    if (\Module\duser\Model\Duser::KiemTraQuyen([\Module\duser\Model\Duser::Superadmin, \Module\duser\Model\Duser::admin]) == true) {
    ?>
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Tạo Lại Mật Khẩu</h3>
                </div>
                <div class="box-body">
                    <form action="" method="POST" class="form-horizontal">
                        <div class="form-group">
                            <label for="inputName" class="col-sm-4 control-label">Nhập Mật Khẩu</label>
                            <div class="col-sm-6">
                                <input type="hidden" readonly="readonly" value="<?php echo $User->Username; ?>" name="Username">
                                <input style="font-size: 20px;" ng-model="Matkhau" type="{{typePasswod}}" name="Password" id="password" class="form-control" placeholder="Mật khẩu">
                                <button type="button" ng-click="SetTypePassword()" class="XemMatKhau btn btn-success"><i class="fa fa-eye"></i></button>
                                <button type="button" ng-click="SetPassword()" id="TaoMatKhau" data-target="#password" class="btn btn-success">
                                    Tạo mật khẩu
                                </button>
                            </div>
                        </div>
                        <div class="col-sm-offset-4 col-sm-6">
                            <button type="submit" name="ResetPassword" class="btn btn-success">Cập Nhật</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    <?php
    }
    ?>
    <div class="clearfix"></div>
</div>