<?php
$TinhThanh = new Model\TinhThanh\TinhThanh();
$pageNumber = isset($_GET["HienThi"]) ? intval($_GET["HienThi"]) : 10;
$indexPage = isset($_GET["IndexPage"]) ? intval($_GET["IndexPage"]) : 1;
$total = 0;
$name = "";
$TinhThanhs = $TinhThanh->GetAllPT($name, $total, $indexPage, $pageNumber);
?>
<div class="container-fluid" ng-controller="diachiController" >
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Tỉnh Thành Phố</h3>
            <div class="box-tools">
                <a href="#" class="btn btn-primary" ><i class="fa fa-plus" ></i></a>
            </div>
        </div>
        <div class="box-body">
            <form action="/tinhthanh/index/index/" enctype="multipart/form-data" method="GET" >
                <div class="d-flex">
                    <div class="col-md-3">
                        <?php
                        \Model\PhanTrangForm::IndexPage($indexPage, ["id" => "indexPages", "onchange" => "this.form.submit()"])->render();
                        \Model\PhanTrangForm::TuKhoa($name, ["name" => "TuKhoa", "id" => "TimKiemTuKhoa", "placeholder" => "Từ Khoá", "onchange" => "this.form.submit()"])->renderHTML();
                        ?>
                    </div>
                    <div class="col-md-1">
                        <div class="row">
                            <?php
                            \Model\PhanTrangForm::HienThi($pageNumber, ["name" => "HienThi", "id" => "Number", "onchange" => "this.form.submit()"])->renderHTML();
                            ?>
                        </div>
                    </div>

                </div>
            </form>

            <form action="" enctype="multipart/form-data" method="POST" >
                <table class="table table-bordered" >
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Parent</th>
                            <th>IsActive</th>
                            <th>Note</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($TinhThanhs as $k => $tt) {
                            $_TT = new Model\TinhThanh\TinhThanh($tt);
                            ?>
                            <tr>
                                <th><?php echo $k + 1; ?></th>
                                <th><?php echo $_TT->Id; ?></th>
                                <th><?php echo $_TT->Name; ?></th>
                                <th><?php echo $_TT->Parents()->Name != null ? $_TT->Parents()->Name : "Cấp Tỉnh"; ?></th>
                                <th><?php echo $_TT->isActive(); ?></th>
                                <th><?php echo $_TT->Note; ?></th>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                </table>
                <button type="button" ng-click="savelocation()"  >lưu</button>
            </form>

        </div>
    </div>



</div>
