<style>
    @media print {

        .no-print,
        .no-print * {
            display: none !important;
        }
    }


    .content-orderdetail {
        font-size: 18px;
    }

    .main {
        font-size: 18px;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    .salesslip {
        width: 380px;
        margin: auto;
        padding: 5px;
    }

    .shop {
        text-align: center;
    }

    /* ------------------------------ */
    .temporary table tr td:last-child {
        text-align: right;
    }

    .temporary table {
        width: 100%;
    }

    .temporary {
        justify-content: space-between;
    }

    /* ------------------------------ */
    .content {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    /* ------------------------------ */
    .total-order {
        display: flex;
        flex-basis: 50%;
        justify-content: space-between;
    }

    .total-order p {
        font-size: 17px;
        margin: 5px 0;
    }

    /* ------------------------------ */
    .footer {
        text-align: center;
    }

    .btn {
        margin-left: 50%;
        padding: 5px 30px;
        transform: translateX(-50%);
        border-radius: 10px;
        border: 1px solid #9e9e9e;
    }

    .btn:hover {
        color: #000;
        cursor: pointer;
        background-color: #6b6565ba;
    }

    .products {
        width: 100%;
    }

    .products tr {
        border-bottom: 1px dotted #aaa;
    }

    .products>tr>td:last-child {
        text-align: right;
        font-weight: bold;
    }
</style>

<?php

use Common\Common;
use Model\Products;
use Model\ThanhToan;
use Model\ThanhToan\BenhNhan;
use Module\cart\Model\Order;
use Module\duser\KhachHang\KhachHang;
use Picqer\Barcode\BarcodeGeneratorPNG;

$generator = new BarcodeGeneratorPNG();
// $generator = new Picqer\Barcode\BarcodeGeneratorPNG();
$id = $_Param[0];
$order = new Order($id);
$thanhToan = new ThanhToan();
$orderDetail = $order->orderDetailbyid($id);
$thongTinKhachHang = $thanhToan->GetTTBenhnhan($order->Name);
$soTienBangChu = Common::Number2words($order->TotalPrice) . " đồng";


?>

<div class="main ">
    <div class="salesslip">
        <div class="shop"><br>  
            <h2 style="font-weight: bold;">PHIẾU BÁN HÀNG</h2>
            <h4 style="font-style: italic; font-weight: 300; margin: 10px 0;">
                Ngày <span style="border-bottom: 2px dotted #aaa;"><?php echo date("d", time()) ?></span>
                tháng <span style="border-bottom: 2px dotted #aaa;"> <?php echo date("m", time()) ?> </span>
                năm <span style="border-bottom: 2px dotted #aaa;"><?php echo date("Y", time()) ?> </span>
            </h4> 
            <?php
            $string = $order->Id;
            echo '<img style="height:50px;
            " src="data:image/png;base64,' . base64_encode($generator->getBarcode($string, BarcodeGeneratorPNG::TYPE_CODE_128)) . '">';
            ?>
            <p>Mã Phiếu: <?php echo $string; ?></p>
        </div>
        <hr style="border-bottom: 1px dashed #aaa;margin: 0px;">
        <!---------------------------------->
        <div class="temporary">
            <table style="width:100%;">
                <tr>
                    <td class="temporary-title">Họ và tên:</td>
                    <td class="temporary-title"><?php echo $thongTinKhachHang["HotenBN"] ?? $order->Name; ?></td>
                </tr>
                <tr>
                    <td class="temporary-title">Nhân viên phục vụ:</td>
                    <td class="temporary-title"><?php echo $order->Saler ?? "N/A"; ?></td>
                </tr>
                <tr>
                    <td class="temporary-title">Năm sinh:</td>
                    <td class="temporary-title"><?php echo $thongTinKhachHang["Ngaysinh"] ?? $order->NgaySinh; ?></td>
                </tr>
                <tr>
                    <td class="temporary-title">Khoa:</td>
                    <td class="temporary-title"><?php echo $thongTinKhachHang["Tiensubenh"] ?? $order->KhoaBenh; ?></td>
                </tr>
                <tr>
                    <td class="temporary-title">Mã bệnh nhân:</td>
                    <td class="temporary-title"><?php echo $thongTinKhachHang["Nhommau"] ?? ""; ?></td>
                </tr>
                <tr>
                    <td class="temporary-title">Tình Trạng:</td>
                    <td class="temporary-title">
                        <b><?php echo $order->Status() ?? ""; ?></b>
                    </td>
                </tr>
                <tr>
                    <td class="temporary-title">Số dư tài khoản:</td>
                    <td class="temporary-title">
                        <?php
                        echo  Common::MoneyFomat($thongTinKhachHang["Soduthe"] ?? 0);
                        ?>
                    </td>
                </tr>
            </table>
        </div>
        <hr style="border-bottom: 1px dashed #aaa;margin: 0px;">
        <div class="content content-orderdetail" style="padding: 0 5px;">
            <table style="width: 100%">
                <tr>
                    <th class="temporary-title"><b>Mã</b></th>
                    <th><b>Tên hàng hóa</b></th>
                    <th><b>SL</b></th>
                    <th style="text-align: center;"><b>Đơn giá</b></th>
                    <th style="text-align: right;"><b>Thành tiền</b></th>
                </tr>
                <?php
                foreach ($orderDetail as $key => $value) {
                    $p = new Products($value["IdProduct"]);
                ?>
                    <tr>
                        <td class="temporary-title"><?php echo $p->Code ?></td>
                        <td><?php echo $p->nameProduct ?></td>
                        <td><?php echo $value["Number"]; ?></td>
                        <td style="text-align: center;">
                            <?php
                            echo Common::MoneyFomat($value["Price"]);
                            ?>
                        </td>
                        <td style="text-align: right;">
                            <?php echo  Common::MoneyFomat($value["Price"] * $value["Number"]); ?>
                        </td>
                    </tr>
                <?php
                }
                ?>
            </table>
        </div>
        <hr style="border-bottom: 1px dashed #aaa;margin-top: 5px;margin-bottom: 5px;">
        <div style="">
            <div class="total-order">
                <table class="products">
                    <tr>
                        <td>Tổng tiền:</td>
                        <td><b><?php echo Common::MoneyFomat($order->TotalPrice); ?></b></td>
                    </tr>
                    <tr>
                        <td colspan="2">Tổng tiền bằng chữ:
                            <b><?php echo $soTienBangChu; ?></b>
                        </td>
                    </tr>
                    <!-- <tr>
                        <td>
                            Số tiền còn lại trong thẻ bằng số:
                        </td>
                        <td><b><?php echo $order->TotalPrice; ?></b></td>
                    </tr> -->
                </table>
            </div>
            <div class="footer">
                <p style="font-size:16px;margin: 10px 0;">Cảm ơn và chúc các bạn một ngày tuyệt vời !</p>
            </div>
            <button type="submit" onclick="window.print()" class="no-print btn">
                Print
            </button>
        </div>
    </div>
</div>