<style>
    @media print {

        .no-print,
        .no-print * {
            display: none !important;
        }
    }

    .main {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    .salesslip {
        width: 400px;
        margin: auto;
    }

    .shop {
        text-align: center;
    }

    /* ------------------------------ */
    .temporary table tr td:last-child {
        text-align: right;
    }

    .temporary table {
        width: 100%;
    }

    .temporary {
        justify-content: space-between;
    }

    /* ------------------------------ */
    .content {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    /* ------------------------------ */
    .total-order {
        display: flex;
        flex-basis: 50%;
        justify-content: space-between;
    }

    .total-order p {
        font-size: 17px;
        margin: 5px 0;
    }

    /* ------------------------------ */
    .footer {
        text-align: center;
    }

    .btn {
        margin-left: 50%;
        padding: 5px 30px;
        transform: translateX(-50%);
        border-radius: 10px;
        border: 1px solid #9e9e9e;
    }

    .btn:hover {
        color: #000;
        cursor: pointer;
        background-color: #6b6565ba;
    }

    .products {
        width: 100%;
    }

    .products tr {
        border-bottom: 1px dotted #aaa;
    }

    .products>tr>td:last-child {
        text-align: right;
        font-weight: bold;
    }
</style>

<?php

use Common\Common;
use Model\Products;
use Module\cart\Model\Order;

$id = $_Param[0];
$order = new Order($id);
$orderDetail = $order->orderDetailbyid($id);
// var_dump($orderDetail);
$soTienBangChu = Common::Number2words($order->TotalPrice);
?>

<div class="main">
    <div class="salesslip">
        <div class="shop"><br>
            <h2 style="font-weight: bold;">PHIẾU BÁN HÀNG</h2>
            <h4 style="font-style: italic; font-weight: 300; margin: 10px 0;">
                Ngày <?php echo date("d", time()) ?>
                tháng <?php echo date("m", time()) ?>
                năm <?php echo date("Y", time()) ?>
            </h4>
            <!-- <span class="shop-add">523 Nguyễn Văn Khối, Phường 8 <br>
                    Quận Gò Vấp, Thành Phố Hồ Chí Minh, 7000
                </span><br>
                <span class="shop-tel">SĐT : 0949797755</span><br><br> -->
        </div>
        <hr style="border-bottom: 1px dashed #aaa;margin: 0px;">
        <!---------------------------------->
        <div class="temporary">
            <table style="width:100%;">
                <tr>
                    <td class="temporary-title">Họ và Tên BN:</td>
                    <td class="temporary-title"><?php echo $order->Name; ?></td>
                </tr>
                <tr>
                    <td class="temporary-title">Nhân viên phục vụ:</td>
                    <td class="temporary-title"><?php echo $order->Saler; ?></td>
                </tr>
                <tr>
                    <td class="temporary-title">Năm sinh:</td>
                    <td class="temporary-title">N/A</td>
                </tr>
                <tr>
                    <td class="temporary-title">Khoa:</td>
                    <td class="temporary-title">N/A</td>
                </tr>
                <tr>
                    <td class="temporary-title">Mã bệnh án:</td>
                    <td class="temporary-title">N/A</td>
                </tr>
            </table>
        </div>
        <hr style="border-bottom: 1px dashed #aaa;margin: 0px;">
        <div class="content" style="padding: 0 5px;">
            <table style="width: 100%">
                <tr>
                    <td class="temporary-title">Mã</td>
                    <td>Tên hàng hóa</td>
                    <td>SL</td>
                    <td style="text-align: center;">Đơn giá</td>
                    <td style="text-align: right;">Thành Tiền</td>
                </tr>
                <?php
                foreach ($orderDetail as $key => $value) {
                    $p = new Products($value["IdProduct"]);
                ?>
                    <tr>
                        <td class="temporary-title"><?php echo $p->ID ?></td>
                        <td><?php echo $p->nameProduct ?></td>
                        <td><?php echo $value["Number"]; ?></td>
                        <td style="text-align: center;"><?php echo $value["Price"]; ?></td>
                        <td style="text-align: right;"><?php echo $value["Price"] * $value["Number"]; ?></td>
                    </tr>
                <?php
                }
                ?>

            </table>
        </div>
        <hr style="border-bottom: 1px dashed #aaa;margin-top: 5px;margin-bottom: 5px;">
        <div style="">
            <div class="total-order" style=" ">
                <table class="products">
                    <tr>
                        <td>Tổng tiền:</td>
                        <td><b><?php echo $order->TotalPrice; ?></b></td>
                    </tr>
                    <tr>
                        <td colspan="2">Tổng tiền bằng chữ:
                            <b><?php echo $soTienBangChu; ?></b>
                        </td>
                    </tr>
                    <!-- <tr>
                        <td>
                            Số tiền còn lại trong thẻ bằng số:
                        </td>
                        <td><b><?php echo $order->TotalPrice; ?></b></td>
                    </tr> -->
                </table>
            </div>
            <div class="footer">
                <p style="font-size:16px;margin: 10px 0;">Cảm ơn và chúc các bạn một ngày tuyệt vời !</p>
            </div>
            <button type="submit" onclick="window.print()" class="no-print btn">
                Print
            </button>
        </div>
    </div>
</div>