<div class="row " ng-controller="mnewsController"  >
    <section class="col-md-12" >
        <div class="box box-primary ">
            <div class="box-header ">
                <h3 class="box-title">Danh Sách Bài Viết</h3>
            </div>
            <div class="box-body ">
                <div class="" >
                    <table class="table table-bordered table-hover"  >
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Tiêu Đề</th>
                                <th>Danh Mục</th>
                                <th>Số Thứ Tự</th>
                                <th>Ẩn Hiển</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="itemnews in _news.data" >
                                <th>{{$index + 1}}</th>
                                <th>{{itemnews.Name}}</th>
                                <th>{{itemnews.Page.Name}}</th>
                                <th>{{itemnews.Stt}}</th>
                                <th>{{itemnews.AnHien}}</th>
                                <th>
                                    <div class="btn-group" >
                                        <a href="/mnews/editnews/{{itemnews.ID}}" class="btn-sm btn btn-success"  >Sửa</a>
                                        <div style="display: inline-table;" class=" bakco-modaldelete" ng-init="modaldeleteInit('Xóa', 'Thông Báo', 'Bạn có muốn xóa trang này', '/mnews/deletenews/' + itemnews.ID, itemnews.ID)" ></div>
                                    </div>
                                </th>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>STT</th>
                                <th>Tiêu Đề</th>
                                <th>Danh Mục</th>
                                <th>Số Thứ Tự</th>
                                <th>Ẩn Hiển</th>
                                <th></th>
                            </tr>
                        </tfoot>

                    </table>
                </div>
                <phan-trang1 pages-index="_news.pageIndex"
                             pages-number="_news.pageNumber"
                             pages-total="_news.totalPages"
                             pages-link="/mnews/index/#!/[i]"
                             pages-params='_news.Params'
                             on-click=""></phan-trang1>
            </div>
        </div>
    </section>
</div>