
<div class="row " ng-controller="mnewsController"  >
    <section class="col-md-12" >
        <a href="/mnews/addnews/" class="btn btn-primary" >
            Thêm Mới <i class="fa fa-plus" ></i>
        </a>
        <h3 >Danh Sách Bài Viết</h3>
        <div class="box box-primary ">
            <div class="box-header ">
                <div class="">
                    <a ng-class="_Seach.isShow == 'All' ? 'active btn-primary' : ''" ng-click="TimSanPhamIsShow('All')" class="btn btn-default" >
                        Tất Cả
                    </a>
                    <a ng-class="_Seach.isShow == '1' ? 'active btn-primary' : ''" ng-click="TimSanPhamIsShow('1')" class="btn btn-default" >Hiện</a>
                    <a ng-class="_Seach.isShow == '0' ? 'active btn-primary' : ''" ng-click="TimSanPhamIsShow('0')" class="btn btn-default" >Ẩn</a>
                </div>
                <div class="pull-right box-tools">
                    <div class="d-flex">
                        <input ng-change="SeachNews(_Seach, 1, 10)" ng-model="_Seach.name" class="form-control" >
                        <button ng-click="SeachNews(_Seach, 1, 10)" class="btn btn-success" ><i class="fa fa-search" ></i></button>
                    </div>
                </div>
            </div>
            <div class="box-body ">
                <div class="" >
                    <table class="table table-bordered table-hover"  >
                        <thead>
                            <tr>
                                <th style="width: 50px;" >STT</th>
                                <th>Tiêu Đề</th>
                                <th>Danh Mục</th>
                                <th>Số Thứ Tự</th>
                                <th>Ẩn Hiển</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="itemnews in _news.data" >
                                <th>{{$index + 1}}</th>
                                <th>{{itemnews.Name}}</th>
                                <th>{{itemnews.Page.Name}}</th>
                                <th>{{itemnews.Stt}}</th>
                                <th>{{itemnews.AnHienTitle}}</th>
                                <th>
                                    <div class="btn-group" >
                                        <a ng-click="getNewsById(itemnews.ID)" class="btn btn-sm btn-primary" target="_self" data-toggle="modal" href='#SuaNhanTinTuc'>Sửa nhanh</a>
                                        <a href="/mnews/editnews/{{itemnews.ID}}" class="btn-sm btn btn-success"  >Sửa</a>
                                        <div style="display: inline-table;" class=" bakco-modaldelete" ng-init="modaldeleteInit('Xóa', 'Thông Báo', 'Bạn có muốn xóa trang này', '/mnews/deletenews/' + itemnews.ID, itemnews.ID)" ></div>
                                    </div>
                                </th>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>STT</th>
                                <th>Tiêu Đề</th>
                                <th>Danh Mục</th>
                                <th>Số Thứ Tự</th>
                                <th>Ẩn Hiển</th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <div class="d-flex">
                    <select style="width: 80px;margin-top: 10px;" class="form-control" ng-change="SeachNews(_Seach, 1, _news.pageNumber)" ng-model="_news.pageNumber" >
                        <option value="10" >10</option>
                        <option value="20" >20</option>
                        <option value="50" >50</option>
                    </select>
                    <phan-trang1 pages-index="_news.pageIndex"
                                 pages-number="_news.pageNumber"
                                 pages-total="_news.totalPages"
                                 pages-link=""
                                 pages-params='_news.Params'
                                 on-click="SeachNews(Params,pagesIndex,pagesNumber)"></phan-trang1>
                </div>
            </div>
        </div>
    </section>

    <div class="modal fade" id="SuaNhanTinTuc">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Sửa Nhanh</h4>
                </div>
                <div class="modal-body">
                    <form-sua-nhanh-tin-tuc></form-sua-nhanh-tin-tuc>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" ng-click="SaveNhanhTinTuc(_newsDetail)" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</div>