<?php
$Mode_brand = new Model\Brand\BrandService();
$total = 0;
$name = !empty($_GET["name"]) ? $_GET["name"] : "";
$indexPage = !empty($_GET["index"]) ? $_GET["index"] : 1;
$pageNumber = !empty($_GET["number"]) ? $_GET["number"] : 10;
$brands = $Mode_brand->GetAllPT($name, $total, $indexPage, $pageNumber);
?>
<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Danh sách thương hiệu</h3>
        <div class="box-tools">
            <a href="/brand/post" class="btn btn-primary" ><i class="fa fa-plus" ></i></a>
        </div>
    </div>
    <div class="box-body">
        <table class="table table-bordered" >
            <thead>
                <tr>
                    <th style="max-width: 50px" class="text-center" >#</th>
                    <th>Thương Hiệu</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($brands as $k => $value) {
                    $_brand = new Model\Brand\BrandService($value);
                    ?>
                    <tr>
                        <td><?php echo \lib\Common::PhanTrangIndex($k, $pageNumber, $indexPage) ?></td>
                        <td   >
                            <div class="d-flex" >
                                <img style="height: 50px;margin-right: 10px;" src="<?php echo $_brand->Images ?>" class="img img-responsive" alt="alt" title="alt" >
                                <div>
                                    <h3 style="margin: 0px;font-size: 16px;font-weight: bold;" ><?php echo $_brand->Name ?></h3>
                                    <p>
                                        <a href="<?php echo $_brand->linkPut() ?>"   >Sửa</a> |
                                        <a href="<?php echo $_brand->linkDelete() ?>" title="Bạn Muốn Xóa Thương Hiệu Này" class="btn-xoa" >Xóa</a>
                                    </p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </tbody>
            <tfoot>
                <tr>
                    <th>#</th>
                    <th>Thương Hiệu</th>
                </tr>
            </tfoot>

        </table>
        <?php
        $DuongDan = "/brand/index/?index=[i]&number={$pageNumber}&name={$name}";
        $TongTrang = ceil($total / $pageNumber);
        echo \lib\Common::PhanTrang($TongTrang, $indexPage, $DuongDan);
        ?>
    </div>
</div>