<div class="row">
    <div class="col-md-6">
        <form action="" enctype="multipart/form-data" method="POST" >
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Thêm</h3>
                </div>
                <div class="box-body">
                    <?php
                    Model\Brand\BrandForm::Name()->renderHTML();
                    Model\Brand\BrandForm::Title()->renderHTML();
                    Model\Brand\BrandForm::Keyword()->renderHTML();
                    Model\Brand\BrandForm::Desc()->renderHTML();
                    ?>
                    <div class="form-group">
                        <label for="">Hình Ảnh</label>
                        <div class="d-flex">
                            <?php
                            Model\Brand\BrandForm::Images("", "HinhBrand")->render();
                            ?>
                            <button  onclick="BrowseServer('Images:/Brand/', 'HinhBrand')" type="button" class="btn btn-primary" >Chọn Hình</button>
                        </div>
                    </div>

                </div>
                <div class="box-footer text-right">
                    <button type="submit" name="Save" class=" btn btn-primary" >Thêm</button>
                </div>
            </div>
        </form>
    </div>
</div>


