<?php
$view_theme = new theme\home\functionLayout();
$Category = $data["Category"];
$cat = new \Model\Category();
$listCatID = [$Category->catID];
$cat->AllCategoryByParentID([$Category->catID], $listCatID);
$product = new \Model\Products();
//var_dump($Category);
//var_dump($data["Pages"]);
$Pages = intval($data["Pages"]);
$Number = 32;
$DSProduct = $product->ProductsByCatID($listCatID, $Pages, $Number, $sum);
?>
<?php
$view_theme->categorySlider();
?>
<!-- view-product-list-->
<div class="col-md-9">
    <div id="view-product-list" class="view-product-list">
        <h2 class="page-heading">
            <span class="page-heading-title"><?php echo $Category->catName; ?></span>
        </h2>
        <!-- PRODUCT LIST -->
        <ul class="row product-list grid">
            <?php
            if ($DSProduct)
                foreach ($DSProduct as $_Poroduct) {
            ?>
                <li class="col-sx-12 col-sm-3">
                    <?php
                    $view_theme->product($_Poroduct);
                    ?>
                </li>
            <?php
                }
            ?>
        </ul>
    </div>
    <div class="sortPagiBar  pull-left">
        <div class="bottom-pagination">
            <nav class="row">
                <?php
                $DuongDan = $Category->linkCurentCategory() . '/[i]';
                echo lib\Common::PhanTrangTheoSL($sum, $Number, $Pages, $DuongDan);
                ?>
            </nav>
        </div>
    </div>
</div>
<div class="col-md-3">
    <table class="table table-bordered table-responsive cart_summary">
        <thead>
            <tr style="background-color: gold;">
                <th class="" style="padding: 0;padding-left:10px;padding-top: 5px;padding-right: 10px;padding-bottom: 5px;">
                    <a class="pull-right" ng-click="XoaGioHang()" style="color: #000"><i class="fa fa-2x fa-trash-o"></i></a>
                    <h3 style="line-height: 30px;font-weight: bold;">Sản phẩm đã chọn</h3>
                </th>
            </tr>
            <tr>
                <th class="" style="background-color: #fff;padding: 0;padding-left:10px;padding-top: 5px;">
                    <form ng-submit="SanPhamByCode(MaSanPham)">
                        <input autofocus type="text" ng-model="MaSanPham" style="background: #fff;" placeholder="Thêm theo mã sản phẩm" />
                    </form>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="items in _Cart.Product">
                <td class="cart_description">
                    <div class="d-flex giohang">
                        <div class="imagesSp hidden">
                            <a href="#">
                                <img style="width: 70px;margin-right: 10px" src="{{items.UrlHinh}}" alt="{{items.nameProduct}}">
                            </a>
                        </div>
                        <div class="" style="width: 100%;padding-right: 10px;">
                            <a class="btn btn-danger btn-xs pull-right" ng-click="removeProductCart(items.ID)">Xóa</a>
                            <h2 class="product-name">
                                {{items.nameProduct}}
                            </h2>
                            <small class="cart_ref">Id: #{{items.Code}}</small><br>
                            <p><span ng-bind-html="items.priceVnd"></span></p>
                        </div>
                        <div class="qty" style="min-width: 76px;">
                            <input style="" class="inputcartnumber form-control input-sm" type="text" ng-value="items.Number">
                            <div class=" btn-group-xs">
                                <a ng-click="minuNumberProduct(items.ID)" class="btn-block btn-cart btn-primary">
                                    <i class="fa fa-minus"></i>
                                </a>
                                <a ng-click="plusNumberProduct(items.ID)" class="btn-block btn-cart btn-primary">
                                    <i class="fa fa-plus"></i>
                                </a>
                            </div>
                        </div>
                        <div class="hidden-sm hidden-xs" style="width: 120px;padding-left: 10px;">
                            <strong ng-bind-html="ToHtml(items.ThanhTienVND)"></strong>
                        </div>

                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <p class="text-right">Tổng Tiền: <b ng-bind-html="_Cart.TotalPriceVND"></b></p>
                </td>
            </tr>

        </tbody>
    </table>
    <div class="cart_navigation">
        <?php
        if (!isset($_SESSION[QuanTri])) {
        ?>
            <a class="btn next-btn btn-primary" href="/index/dathang">Đặt hàng</a>
        <?php
        } else {
        ?>
            <a class="btn next-btn btn-primary" href="/index/thanhtoan">Thanh toán</a>
        <?php
        }
        ?>

    </div>
</div>
<!-- ./view-product-list-->
<div class="clearfix"></div> 