<?php

use Module\user\Model\Users\UserForm;
?>
<div class="container" style="margin-top: 15px;" >
    <div class="row" >
        <div class="col-md-8" >
            <p class="text-center" style="color: red;text-transform: capitalize" >hotline: __Hotline__ <br> Email: __Email__   <br> Zalo: __SDT__</p>
        </div>
        <div class="col-md-4" >
            <h3 class="text-center" >Đăng Ký Tài Khoản</h3>
            <form action="" enctype="multipart/form-data" method="POST" >
                <?php
                UserForm::Name()->renderHTML();
                UserForm::Phone()->renderHTML();
                UserForm::Email()->renderHTML();
                UserForm::Username()->renderHTML();
                UserForm::Password()->renderHTML();
                UserForm::RePassword()->renderHTML();
                ?>
                <div class="form-group text-center">
                    <label for=""></label>
                    <button name="btnDangNhap" class="btn btn-primary" >Đăng Ký</button>
                </div>
            </form>
        </div>
    </div>
</div>
