  <div class="container">
      <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-6">
              <h2>Đặt hàng</h2>
              <table style="margin-top: 20px;" class="table table-bordered table-responsive cart_summary">
                  <thead>
                      <tr style="background-color: gold;padding-bottom: 5px;padding-top: 5px;">
                          <th class="">
                              <h3>Sản Phẩm</h3>
                          </th>
                      </tr>
                  </thead>
                  <tbody>
                      <tr ng-repeat="items  in _Cart.Product">
                          <td class="cart_description">
                              <div class="d-flex giohang">
                                  <div class="imagesSp hidden">
                                      <a href="#">
                                          <img style="width: 70px;margin-right: 10px" src="{{items.UrlHinh}}" alt="{{items.nameProduct}}">
                                      </a>
                                  </div>
                                  <div class="" style="width: 100%;padding-right: 10px;">
                                      <h2 class="product-name">
                                          {{items.nameProduct}}
                                      </h2>
                                      <small class="cart_ref">Id : #{{items.Code}}</small><br>

                                      <p><span ng-bind-html="items.priceVnd"></span></p>
                                  </div>
                                  <div class="qty" style="min-width: 76px;">
                                      <input class="inputcartnumber form-control input-sm" type="text" ng-value="items.Number">
                                  </div>
                                  <div class="hidden-sm hidden-xs" style="width: 120px;padding-left: 10px;">
                                      <strong ng-bind-html="ToHtml(items.ThanhTienVND)"></strong>
                                  </div>
                              </div>
                          </td>
                      </tr>
                      <tr>
                          <td>
                              <p class="text-right">Tổng Tiền: <b ng-bind-html="_Cart.TotalPriceVND"></b></p>
                          </td>
                      </tr>

                  </tbody>
              </table>
              <a class="btn btn-primary" href="/">
                  <i class="fa fa-arrow-left" aria-hidden="true"></i>
                  Quay lại
              </a>

              <a class="btn btn-primary pull-right" href="/index/taophieu">
                  Tiếp tục đặt hàng
                  <i class="fa fa-arrow-right" aria-hidden="true"></i>
              </a>
          </div>
      </div>
  </div>
  <script>
      $(function() {
          document.getElementById("MaThe").focus();
      })
  </script>