<?php
$DanhSacDanhMuc = $functionLayout->GetConfigByKey(theme\home\functionLayout::DanMucSanPham);
if (\Model\Driver::is_mobile() == FALSE) {
    if ($DanhSacDanhMuc) {
        foreach ($DanhSacDanhMuc as $k => $danhmuc) {
            $cat = new \Model\Category($danhmuc["DanhMuc"]);
            $listCatID = [$danhmuc["DanhMuc"]];
            $cat->AllCategoryByParentID([$danhmuc["DanhMuc"]], $listCatID);
            $product = new \Model\Products();
            $Number = 32;
            $DanhSachSanPham = $product->ProductsByCatID($listCatID, 1, $Number, $sum);
            ?>
            <div class="DanhMuc-panel" style="margin-top: 40px;margin-bottom: 40px;" >
                <div class="container">
                    <div class="panel-heading">
                        <a href="<?php echo $cat->linkCurentCategory(); ?>"  class="hidden-sm hidden-xs pull-right" > Xem Tất Cả <i class="fa fa-angle-double-right"></i> </a>
                        <h2 class="text-center" >
                            <span ><?php echo $cat->catName; ?></span>
                        </h2>
                    </div>
                    <ul class="product-list owl-carousel" data-dots="false" data-loop="true" data-nav="true" data-margin="20"
                        data-autoplayTimeout="1000" data-autoplay="true" data-autoplayHoverPause="true" data-lazy-load="true"
                        data-responsive='{"0":{"items":1},"600":{"items":3},"1000":{"items":5}}'>
                            <?php
                            if ($DanhSachSanPham) {
                                foreach ($DanhSachSanPham as $sp) {
                                    $_Sp = new \Model\Products($sp);
                                    ?>
                                <li>
                                    <div class="left-block product-carosel">
                                        <a href="<?php echo $_Sp->linkProduct() ?>">
                                            <img onerror="this.src='/public/no-image.jpg'" class="img-product img-responsive"  loading="lazy" alt="<?php echo $_Sp->nameProduct ?>" src="<?php echo $_Sp->UrlHinh(); ?>" />
                                        </a>
                                        <div class="add-to-cart">
                                            <?php
                                            $_Sp->btnGioHang();
                                            ?>
                                        </div>
                                        <div class="group-price hidden">
                                            <span class="product-new">NEW</span>
                                            <span class="product-sale">Sale</span>
                                        </div>
                                    </div>
                                    <div class="right-block">
                                        <h2 class="product-name"><a href="<?php echo $_Sp->linkProduct() ?>"><?php echo $_Sp->nameProduct ?></a></h2>
                                        <div class="content_price">
                                            <span class="price product-price"><?php echo $_Sp->Price(); ?></span>
                                            <span class="price old-price"><?php echo $_Sp->oldPrice(); ?></span>
                                        </div>
                                        <div class="product-star hidden">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                    </div>
                                </li>
                                <?php
                            }
                        }
                        ?>


                    </ul>
                </div>
            </div>
            <?php
        }
    }
} else {
    if ($DanhSacDanhMuc) {
        foreach ($DanhSacDanhMuc as $k => $danhmuc) {
            $cat = new \Model\Category($danhmuc["DanhMuc"]);
            $listCatID = [$danhmuc["DanhMuc"]];
            $cat->AllCategoryByParentID([$danhmuc["DanhMuc"]], $listCatID);
            $product = new \Model\Products();
            $Number = 32;
            $DanhSachSanPham = $product->ProductsByCatID($listCatID, 1, $Number, $sum);
            ?>
            <div class="DanhMuc-panel" style="margin-top: 40px;margin-bottom: 40px;" >
                <div class="container">
                    <div class="panel-heading">
                        <a href="<?php echo $cat->linkCurentCategory(); ?>"  class="hidden-sm hidden-xs pull-right" > Xem Tất Cả <i class="fa fa-angle-double-right"></i> </a>
                        <h2 class="text-center" >
                            <span ><?php echo $cat->catName; ?></span>
                        </h2>
                    </div>
                    <ul class="Product-mobie"  >
                        <?php
                        if ($DanhSachSanPham) {
                            foreach ($DanhSachSanPham as $sp) {
                                $_Sp = new \Model\Products($sp);
                                ?>
                                <li class="d-flex">
                                    <div class="left-block ">
                                        <a href="<?php echo $_Sp->linkProduct() ?>">
                                            <img onerror="this.src='/public/no-image.jpg'" class="img-product img img-responsive"  loading="lazy" alt="<?php echo $_Sp->nameProduct ?>" src="<?php echo $_Sp->UrlHinh(); ?>" />
                                        </a>

                                    </div>
                                    <div class="right-block" style="width: 100%;">
                                        <h2 class="product-name"><a href="<?php echo $_Sp->linkProduct() ?>"><?php echo $_Sp->nameProduct ?></a></h2>
                                        <div class="btn pull-right add-to-cart">
                                            <?php
                                            $_Sp->btnGioHang();
                                            ?>
                                        </div>
                                        <div class="content_price">
                                            <span class="price product-price"><?php echo $_Sp->Price(); ?></span>
                                            <span class="price old-price"><?php echo $_Sp->oldPrice(); ?></span>
                                        </div>
                                        <div class="product-star">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                    </div>
                                </li>
                                <?php
                            }
                        }
                        ?>


                    </ul>
                </div>
            </div>
            <?php
        }
    }
}
?>
