<?php


$product = new \Model\Products();
$Number = 32;
$DanhSachSanPham = $product->ProductsAllPT(1, 20, $Tong)
?>
<div class="DanhMuc-panel" style="margin-top: 40px;margin-bottom: 40px;">
    <div class="container">
        <div class="panel-heading">
            <h2 class="text-center">
                Danh sách sản phẩm
            </h2>
        </div>
        <ul class="Product-mobie">
            <?php
            if ($DanhSachSanPham) {
                foreach ($DanhSachSanPham as $sp) {
                    $_Sp = new \Model\Products($sp);
            ?>
                    <li class="d-flex">
                        <div class="left-block ">
                            <a href="<?php echo $_Sp->linkProduct() ?>">
                                <img onerror="this.src='/public/no-image.jpg'" class="img-product img img-responsive" loading="lazy" alt="<?php echo $_Sp->nameProduct ?>" src="<?php echo $_Sp->UrlHinh(); ?>" />
                            </a>
                        </div>
                        <div class="right-block" style="width: 100%;">
                            <h2 class="product-name"><a href="<?php echo $_Sp->linkProduct() ?>"><?php echo $_Sp->nameProduct ?></a></h2>
                            <div class="btn pull-right add-to-cart">
                                <?php
                                $_Sp->btnGioHang();
                                ?>
                            </div>
                            <div class="content_price">
                                <span class="price product-price"><?php echo $_Sp->Price(); ?></span>
                            </div>
                        </div>
                    </li>
            <?php
                }
            }
            ?>


        </ul>
    </div>
</div>