<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

use Model\FormLogin;
?>
<div class="container" ng-init='GetError(<?php echo Model\Error::getAllToJson(); ?>)' style="margin-top: 15px;" >
    <div class="row" >
        <div class="col-md-3" ></div>
        <div class="col-md-6" >
            <h2 class="text-center" >Đăng Nhập</h2>
            <form action="" enctype="multipart/form-data" method="POST" >
                <?php
                FormLogin::Username()->renderHTML();
                FormLogin::Password()->renderHTML();
                ?>
                <div class="alert " ng-show="_Error.Content" ng-class="_Error.Type ? 'alert-' + _Error.Type : ''" >
                    {{_Error.Content}}
                </div>
                <div class="form-group text-center">
                    <label for=""></label>
                    <button name="btnDangNhap" class="btn btn-success" >Đăng Nhập</button>
                </div>
            </form>
            <p class="hidden text-center" style="color: red;text-transform: capitalize" >hotline: __Hotline__ <br> Email: __Email__   <br> Zalo: __SDT__</p>
        </div>
    </div>
</div>
