  <div class="container">
      <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-6">
              <h2>Thanh Toán</h2>
              <?php

                use Model\Error;

                $_er = new Error();
                $er = $_er->getError();
                if ($er) {
                ?>
                  <div class="alert alert-danger" role="alert">
                      <button type="button" class="pull-right close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                      <b><?php echo $er["Content"] ?></b>
                      <p>Vui lòng nạp thêm tiền.</p>
                  </div>
              <?php
                }
                ?>
              <form action="" id="FormThanhToan" method="POST">
                  <div class="form-group">
                      <label for="">Nhập thẻ</label>
                      <input required type="password" style="font-size: 2em;padding: 30px;line-height: 30px;text-align: center;" id="MaThe" type="text" autofocus name="thanhToan[MaThe]" placeholder="Nhập mã thẻ ***" class="form-control">
                  </div>
                  <!-- <button class="btn btn-success">Xác Nhận</button> -->
              </form>
              <table style="margin-top: 20px;" class="table table-bordered table-responsive cart_summary">
                  <thead>
                      <tr style="background-color: gold;padding-bottom: 5px;padding-top: 5px;">
                          <th class="">
                              <h3>Sản Phẩm</h3>
                          </th>
                      </tr>
                  </thead>
                  <tbody>
                      <tr ng-repeat="items  in _Cart.Product">
                          <td class="cart_description">
                              <div class="d-flex giohang">
                                  <div class="imagesSp hidden">
                                      <a href="#">
                                          <img style="width: 70px;margin-right: 10px" src="{{items.UrlHinh}}" alt="{{items.nameProduct}}">
                                      </a>
                                  </div>
                                  <div class="" style="width: 100%;padding-right: 10px;">
                                      <h2 class="product-name">
                                          {{items.nameProduct}}
                                      </h2>
                                      <small class="cart_ref">Id : #{{items.Code}}</small><br>

                                      <p> <span ng-bind-html="items.PriceVND"></span></p>
                                  </div>
                                  <div class="qty" style="min-width: 76px;">
                                      <input class="inputcartnumber form-control input-sm" type="text" ng-value="items.Number">
                                  </div>
                                  <div class="hidden-sm hidden-xs" style="width: 120px;padding-left: 10px;">
                                      <strong ng-bind-html="ToHtml(items.ThanhTienVND)"></strong>
                                  </div>
                              </div>
                          </td>
                      </tr>
                      <tr>
                          <td>
                              <p class="text-right">Tổng Tiền: <b ng-bind-html="_Cart.TotalPriceVND"></b></p>
                          </td>
                      </tr>

                  </tbody>
              </table>

              <a class="btn btn-primary" href="/">
                  <i class="fa fa-arrow-left" aria-hidden="true"></i>
                  Quay lại
              </a>
          </div>
      </div>
  </div>
  <script>
      $(function() {
          var IsSubmit = true;
          $("#FormThanhToan").submit(function() {
              try {
                  if (IsSubmit == false) {
                      console.log("Đã thanh toán");
                      return false;
                  }
                  IsSubmit = false;
                  console.log("đang thanh toán");
                  return true;
              } catch (error) {
                  return false;
              }
          });
          document.getElementById("MaThe").focus();
      })
  </script>