
<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title"><i class="fa fa-gear" ></i> Cài Đặt </h3>
        <div class="box-tools"></div>
    </div>
    <div class="box-body">
        <div class="form-group">
            <p>
                <label>
                    <input name="" type="checkbox" ng-change="setDarkode(darkmode)" ng-model="darkmode" id="darkmode" >
                    Dark mode
                </label>
            </p>
        </div>
    </div>
</div>