<!-- Small boxes (Stat box) -->
<div class="row ">
    <section class="col-md-12 ">
        <div class="box box-solid ">
            <div class="box-body">
                <ul class="bs-glyphicons">
                    <li>
                        <a href="/">
                            <span class="glyphicon glyphicon-shopping-cart"></span>
                            <span class="glyphicon-class">Trang bán hàng</span>
                        </a>
                    </li>
                    <li>
                        <a href="/backend/thongke/">
                            <span class="glyphicon glyphicon-equalizer"></span>
                            <span class="glyphicon-class">Thống Kê</span>
                        </a>
                    </li> 
                    <li>
                        <a href="/backend/thongtinthe/">
                            <span class="glyphicon glyphicon-euro"></span>
                            <span class="glyphicon-class">Tra cứu thông tin thẻ</span>
                        </a>
                    </li>
                    <li>
                        <a href="/cart/mcart/suadonhang/">
                            <span class="glyphicon glyphicon-shopping-cart"></span>
                            <span class="glyphicon-class">Tra cứu đơn hàng</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <!-- <section class="col-md-6 connectedSortable">
        <div class="box box-solid ">
            <div class="box-header bg-green-gradient">
                <i class="fa fa-calendar"></i>
                <h3 class="box-title">Thống kế</h3>
                <div class="pull-right box-tools">
                </div>
            </div>
            <div class="box-body">
                <div>
                    Số đơn hàng:
                </div>
            </div>
        </div>
    </section>
    <section class="col-md-6 connectedSortable">
        <div class="box box-solid ">
            <div class="box-header bg-green-gradient">
                <i class="fa fa-calendar"></i>
                <h3 class="box-title">Calendar</h3>
                <div class="pull-right box-tools">
                    <div class="btn-group">
                        <button class="btn btn-success btn-sm dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bars"></i></button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href="#">Add new event</a></li>
                            <li><a href="#">Clear events</a></li>
                            <li class="divider"></li>
                            <li><a href="#">View calendar</a></li>
                        </ul>
                    </div>
                    <button class="btn btn-success btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-success btn-sm" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body ">
                Noi dung
            </div>
    </section> -->

</div>