 <div class="container ">
     <section class="col-md-12 ">
         <div class="box box-solid ">
             <div class="box-header">
             </div>
             <div class="box-body">
                 <div class="col-md-3"></div>
                 <div class="col-md-6">
                     <?php

                        use Model\ThanhToan;
                        use Model\ThanhToan\BenhNhan;

                        $maThe = $_POST["mathe"] ?? "";
                        $thanhToan = new ThanhToan();
                        $benhNhan = null;
                        $LichSuGiaoDich = [];
                        $thongTin = [];
                        if ($maThe != "") {
                            $thongTin =  $thanhToan->GetTTBenhnhan($maThe);
                            $LichSuGiaoDich =  $thanhToan->GetLichsuGD($maThe);
                            if ($thongTin) {
                                $benhNhan = new BenhNhan($thongTin);
                            }
                        }

                        ?>
                     <h3>Thông tin thẻ</h3>
                     <form action="" method="POST">
                         <div class="d-flex">
                             <input type="password" name="mathe" class="form-control" placeholder="Nhập mã thẻ" value="<?php echo $_REQUEST["mathe"] ?? "" ?>" required="required">
                             <button class="btn btn-success">Tra cứu</button>
                         </div>
                     </form>

                     <table class="table table-hover table-bordered ">
                         <tbody>
                             <?php
                                ob_start();
                                if ($thongTin) {
                                    unset($thongTin["Noicap"]);
                                    unset($thongTin["Ngaycap"]);
                                    foreach ($thongTin as $key => $value) {
                                ?>
                                     <tr>
                                         <td class="text-right">
                                             <?php echo $key ?> :
                                         </td>
                                         <td><?php echo $value ?></td>
                                     </tr>
                             <?php
                                    }
                                }
                                //Soduthe
                                $str = ob_get_clean();
                                $str = BenhNhan::methodToLable($str);
                                echo $str;
                                ?>
                         </tbody>
                     </table>



                 </div>
                 <table class="table table-border table-hover" style="margin-top: 10px;">
                     <tr style="white-space: nowrap;">
                         <td>STT</td>
                         <td>Mã Thẻ</td>
                         <td>Giá trị giao dịch</td>
                         <td>Loại giao dịch</td>
                         <td>Nội dung</td>
                         <td>Thời gian</td>
                         <td></td>
                         <td>Số Dư</td>
                     </tr>
                     <?php
                        if ($LichSuGiaoDich) {
                            foreach ($LichSuGiaoDich as $key => $value) {
                        ?>
                             <tr>
                                 <?php
                                    foreach ($value as $key1 => $item1) {

                                    ?>
                                     <td><?php echo $item1 ?? "";  ?></td>
                                 <?php
                                    }
                                    ?>
                             </tr>
                     <?php
                            }
                        }
                        ?>
                 </table>
             </div>
         </div>
     </section>

 </div>