<?php

use Common\Common;
use Model\FormRender;
use Module\cart\Model\Order;
use Module\duser\Model\Duser;
use PFBC\Element\Select;

$order = new Order();
$KhoaBenh = $order->GetKhaoBenh();
$options[""] = "Tất cả";
foreach ($KhoaBenh as $key => $value) {
    if ($value["KhoaBenh"] != "")
        $options[$value["KhoaBenh"]] = $value["KhoaBenh"];
}
$prop["class"] = "form-control";
$duser = Duser::CurentUsernameAdmin(true);
$prop["value"] = $duser->Groups;
$Danhmuc = new FormRender(new Select("Khoa bệnh", "KhoaBenh", $options, $prop));

if ($duser->Groups ==  Duser::NhanVien) {
    $prop[FormRender::Disabled] = "true";
    $prop["value"] = $duser->KhoaBenh;
    $Danhmuc = new FormRender(new Select("Khoa bệnh", "KhoaBenh", $options, $prop));
}

?>
<div class="row ">
    <section class="col-md-12 ">
        <div class="box box-solid ">
            <div class="box-header">
                <h3 class="box-title">Thống kê Theo Bệnh Nhân
                    <?php echo $total; ?>
                </h3>
            </div>
            <div class="box-body">
                <form action="" method="get">
                    <div class="row">
                        <div class="col-md-3">
                            <label>Từ ngày</label>
                            <input value="<?php echo $_GET["fromDate"] ?? ""; ?>" required class="form-control" type="date" name="fromDate" id="fromDate">
                        </div>
                        <div class="col-md-3">
                            <label>Đến ngày</label>
                            <input value="<?php echo $_GET["toDate"] ?? ""; ?>" required class="form-control" type="date" name="toDate" id="toDate">
                        </div>
                        <div class="col-md-3">
                            <button name="btnLoc" style=" margin-top: 24px;" class="btn btn-success">
                                Lọc
                            </button>
                            <button name="btnExport" style=" margin-top: 24px;" class="btn btn-success">
                                Export
                            </button>
                        </div>
                    </div>
                </form>
                <table style="margin-top: 10px;" class="table table-border">
                    <?php
                    if ($data) {

                        foreach ($data as $index => $row) {
                    ?>
                            <tr>
                                <?php
                                foreach ($row as $k => $v) {
                                ?>
                                    <td><?php echo $v; ?></td>
                                <?php
                                }
                                ?>
                            </tr>
                    <?php
                        }
                    }
                    ?>

                </table>
                <div>
                    <?php
                    $fromDate = $_GET["fromDate"] ?? null;
                    $toDate = $_GET["toDate"] ?? null;
                    $totalPage  = ceil($param["total"] / $param["number"]);
                    $link = "/backend/thongkekhoabenhnhan/?page=[i]&number={$param["number"]}&fromDate={$fromDate}&toDate={$toDate}&btnLoc=";
                    echo Common::PhanTrang($totalPage, $param["page"], $link);
                    ?>
                </div>

            </div>
        </div>
    </section>

</div>