<?php

use Model\FormRender;
use Module\cart\Model\Order;
use Module\duser\Model\Duser;
use PFBC\Element\Select;

$order = new Order();
$Model_OptionsService =  new Model_OptionsService();
$total = 0;
// $options[""] = "Tất cả";
// $options = $Model_OptionsService->GetItems(["GroupsId" => "khoa"], 1, 100, $total);
$options = $Model_OptionsService->GetGroupsToSelect("khoa");

// foreach ($options as $key => $value) {
//     $options[$value["KhoaBenh"]] = $value["KhoaBenh"];
// }
$_GeTKhoaBenh = $_GET["KhoaBenh"] ?? "";
$prop["class"] = "form-control";
$duser = Duser::CurentUsernameAdmin(true);
$prop["value"] = $_GeTKhoaBenh;
$Danhmuc = new FormRender(new Select("Khoa bệnh", "KhoaBenh", $options, $prop));

if ($duser->Groups ==  Duser::NhanVien) {
    // $prop[FormRender::Disabled] = "true";
    // $prop["value"] = $_GeTKhoaBenh; 
    $options = Model_OptionsService::GetGroupsToSelectAndListVal("khoa", $duser->KhoaBenhVal()); 
    $Danhmuc = new FormRender(new Select("Khoa bệnh", "KhoaBenh", $options, $prop));
}

?>
<div class="row ">
    <section class="col-md-12 ">
        <div class="box box-solid ">
            <div class="box-header">
                <h3 class="box-title">Thống kê Theo Khoa</h3>
            </div>
            <div class="box-body">
                <form action="" method="get">
                    <div class="row">
                        <div class="col-md-3">
                            <label>Từ ngày</label>
                            <input value="<?php echo $_GET["fromDate"] ?? ""; ?>" required class="form-control" type="date" name="fromDate" id="fromDate">
                        </div>
                        <div class="col-md-3">
                            <label>Đến ngày</label>
                            <input value="<?php echo $_GET["toDate"] ?? ""; ?>" required class="form-control" type="date" name="toDate" id="toDate">
                        </div>
                        <div class="col-md-3">
                            <?php
                            $Danhmuc->renderHTML();
                            ?>

                        </div>
                        <div class="col-md-3">
                            <button name="btnLoc" style=" margin-top: 24px;" class="btn btn-success">
                                Lọc
                            </button>
                            <button name="btnExport" style=" margin-top: 24px;" class="btn btn-success">
                                Export
                            </button>
                        </div>
                    </div>
                </form>
                <table style="margin-top: 10px;" class="table table-border">
                    <tr>
                        <th>STT</th>
                        <th>Hàng Hóa</th>
                        <th>Mã Danh Mục</th>
                        <th>ĐVT</th>
                        <th>Mã Hàng Hóa</th>
                        <th>Gia bán</th>
                        <th>Khoa</th>
                        <th>Số Lượng</th>
                        <th>Thành Tiền</th>
                        <th>Ghi Chú</th>
                    </tr>
                    <?php
                    if ($data) {

                        foreach ($data as $index => $row) {
                    ?>
                            <tr>
                                <?php
                                foreach ($row as $k => $v) {
                                ?>
                                    <td><?php echo $v; ?></td>
                                <?php
                                }
                                ?>
                            </tr>
                    <?php
                        }
                    }
                    ?>

                </table>

            </div>
        </div>
    </section>

</div>