<?php

use Common\Common;
use Module\cart\Model\BenhNhan;
use Module\cart\Model\BenhNhanFilter;

$_benhNhan = new BenhNhan();
?>
<div class="panel">
    <div class="panel-heading">
        <button id="btnSysn" type="button" class="pull-right btn btn-success">
            Đồng bộ
        </button>
        <h3 class="panel-title">Danh sách bệnh nhân (
            <?php echo $total; ?>)
        </h3>

    </div>
    <div class="panel-body">

        <div role="tabpanel">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active">
                        <a href="#DanhSachBenhNhan" aria-controls="DanhSachBenhNhan" role="tab" data-toggle="tab">
                            Danh Sách Bệnh Nhân
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#ThongKeKhoa" aria-controls="ThongKeKhoa" role="tab" data-toggle="tab">
                            Thống Kê Khoa Bệnh
                        </a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="DanhSachBenhNhan">
                        <div class="table-responsive">

                            <form action="/cart/vieworder/dongbo/" method="get">
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        BenhNhanFilter::khoabenh($_GET["khoabenh"] ?? "")->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-3">
                                        <?php
                                        BenhNhanFilter::SoThe($_GET["SoThe"] ?? "")->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-3">
                                        <button style="margin-top: 25px;" class="btn btn-success">
                                            Lọc
                                        </button>
                                    </div>
                                </div>
                            </form>
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <td>Thao Tác</td>
                                        <?php
                                        foreach($_benhNhan->TitleData() as $key => $title) {
                                            ?>
                                            <td>
                                                <?php echo $title; ?>
                                            </td>
                                            <?php
                                        }
                                        ?>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    if($Items)
                                        foreach($Items as $key => $benhnhan) {
                                            $_benhNhan = new BenhNhan($benhnhan);
                                            $_items = (array)$_benhNhan;
                                            ?>
                                            <tr>
                                                <td>
                                                    <a href="/cart/vieworder/benhnhan/<?php echo $_benhNhan->Sothe; ?>"
                                                        class="btn btn-success">
                                                        Xem
                                                    </a>
                                                    <a onclick="return confirm('Bạn muốn xóa bệnh nhân này?')"
                                                        href="/cart/vieworder/xoabenhnhan/<?php echo $_benhNhan->Sothe; ?>/<?php echo $_benhNhan->MaBN; ?>/"
                                                        class="btn btn-danger">
                                                        Xóa
                                                    </a>
                                                </td>
                                                <?php
                                                foreach($_items as $key => $value) {
                                                    ?>
                                                    <td>
                                                        <?php
                                                        if(is_numeric($value)) {
                                                            echo number_format($value, 0, ".", " ");
                                                        } else {
                                                            echo $value;
                                                        }
                                                        ?>
                                                    </td>
                                                    <?php
                                                }
                                                ?>
                                            </tr>
                                            <?php
                                        }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                        <?php
                        $link = Common::LinkPhanTrang("/cart/vieworder/dongbo/", $params);
                        echo Common::PhanTrang($totalPage, $params["page"], $link);
                        ?>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="ThongKeKhoa">
                        <div class="row">
                            <?php
                            foreach($_benhNhan->BenhNhanTheoKhoaBenh() as $key => $value) {
                                ?>
                                <div class="col-md-3">
                                    <div class="info-box">
                                        <span class="info-box-icon bg-yellow"><i
                                                class="ion ion-ios-people-outline"></i></span>
                                        <div class="info-box-content">
                                            <span class="info-box-text">Khoa:
                                                <?php echo $value["Name"]; ?>
                                            </span>
                                            <span class="info-box-number">Số bệnh nhân:
                                                <?php echo $value["BenhNhan"]; ?>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <?php
                            }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        var index = 0;

        function DongBo(danhSach) {
            // console.log('index', index);
            const danhSachLenh = danhSach.length;
            if (danhSach[index]) {
                const item = danhSach[index];
                $.ajax({
                    type: "get",
                    url: `/cart/vieworder/DongboAjaxById/?id=${item.Name}`,
                    dataType: "json",
                    success: function (response) {
                        index++;
                        console.log('index', index);
                        $("#btnSysn").html(`Đang đồng bộ ${index + 1} / ${danhSachLenh}`);
                        DongBo(danhSach);
                    }
                })
                // DongBo(danhSach);
            } else {
                alert("data đồng bộ xong");
                $("#btnSysn").attr("disabled", false);
                $("#btnSysn").html("Đồng bộ");
            }
        }

        $("#btnSysn").click(function () {
            $("#btnSysn").attr("disabled", true);
            $("#btnSysn").html("Đang đồng bộ");

            $.ajax({
                type: "get",
                url: "/cart/vieworder/GetDongboAjax/",
                dataType: "json",
                success: function (response) {
                    // console.log('response', response);
                    DongBo(response);
                }
            });
        });
    });
</script>