 <div class="panel">
     <div class="panel-heading">
         <h3 class="panel-title">Danh sách bệnh nhân </h3>
     </div>
     <div class="panel-body">
         <table class="table table-bordered">
             <tbody>
                 <tr>
                     <td>MaBN</td>
                     <td>Sothe</td>
                     <td>HotenBN</td>
                     <td>Ngaysinh</td>
                     <td>Gioitinh</td>
                     <td>Diachi</td>
                     <td>Sodienthoai</td>
                     <td>SoCMT</td>
                     <td>Ngaycap</td>
                     <td>Noicap</td>
                     <td>Email</td>
                     <td>Nhommau</td>
                     <td>Tiensubenh</td>
                     <td>Soduthe</td>
                 </tr>
             </tbody>
         </table>
     </div>
 </div>