<?php

use Module\duser\Model\Duser;

?>

<div ng-controller="giohangCotroller" ng-init='DanhSachAllDonHang({"Status": "all", "Keyword":""}, 1, 10)'
    class="box box-primary">
    <div ng-init="TimKiemNhanVien('')">
        <div class="box-header">
            <h3 class="box-title">Danh Sách Đơn Hàng</h3>
            <div class="box-tools">
                <div class="d-flex">
                    <input style="min-width: 300px;" class="form-control" ng-model="_DanhSachDonHang.Params.Keyword"
                        placeholder="Code,Email,Phone">
                    <button ng-click='DanhSachAllDonHang(_DanhSachDonHang.Params, 1, 10)' class="btn btn-primary"><i
                            class="fa fa-search"></i></button>
                </div>
            </div>
        </div>
        <div class="box-body" ng-init="OrderStatus()">
            <button ng-class="_DanhSachDonHang.Params.Status == 'all'?'btn-primary':'btn-default'" class="btn btn-sm "
                ng-click='DanhSachAllDonHang({"KhoaBenh": _khoaBenh,"Saler": _nhanvien,"Status": "all", "Keyword":keyword}, 1, 10)'>Tất
                Cả</button>
            <button ng-class="_DanhSachDonHang.Params.Status == item.Id?'btn-primary':'btn-default'"
                ng-repeat="item in _OrderStatus"
                ng-click='DanhSachAllDonHang({"KhoaBenh": _khoaBenh,"Saler": _nhanvien,"Status": item.Id, "Keyword":keyword}, 1, 10)'
                class="btn btn-sm ">{{item.Name}}</button>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Nhân viên</label>
                        <select ng-change='DanhSachAllDonHang(
                            _DanhSachDonHang.Params
                            , 1, 10)' class="form-control" ng-model="_DanhSachDonHang.Params.Saler">
                            <option value="">Chọn Nhân viên</option>
                            <option ng-repeat="item in _NhanViens.data" value="{{item.Username}}">{{item.Name}}</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Khoa</label>
                        <select ng-change='DanhSachAllDonHang(
                            _DanhSachDonHang.Params, 1, 10)' class="form-control"
                            ng-model="_DanhSachDonHang.Params.KhoaBenh">
                            <option value="">Chọn Khoa Bệnh</option>
                            <option ng-repeat="item in _KhoaBenhs" value="{{item.Val}}">{{item.Name}}</option>
                        </select>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label>Từ ngày</label>
                        <input class="form-control" ng-change='DanhSachAllDonHang(
                            _DanhSachDonHang.Params, 1, 10)' type="date" ng-model="_DanhSachDonHang.Params.TuNgay"
                            placeholder="từ ngày">
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label>Đến ngày</label>
                        <input class="form-control" ng-change='DanhSachAllDonHang(_DanhSachDonHang.Params, 1, 10)'
                            type="date" ng-model="_DanhSachDonHang.Params.DenNgay" placeholder="Đến ngày">
                    </div>
                </div>
            </div>
        </div>
        <table class="table table-bordered table-hover" style="margin-top: 10px;">
            <tr class="bg-blue">
                <td style="width: 50px;">Stt</td>
                <td style="width: 150px;">Ngày Đặt</td>
                <td style="width: 50px;">Code</td>
                <td style="width: 150px;">Khách Hàng</td>
                <td style="width: 150px;">Khoa</td>
                <td>Nhân Viên</td>
                <td style="width: 150px;">Tình Trạng</td>
                <td style="width: 150px;">Tổng Tiền</td>
                <td style="width: 150px;">Action</td>
            </tr>
            <tr ng-repeat="item in _DanhSachDonHang.data">
                <td>{{$index+1}}</td>
                <td>{{item.NgayTao}}</td>
                <td>{{item.Id}}</td>
                <td>{{item.Name}}</td>
                <td>{{item.KhoaBenh}}</td>
                <td>{{item.SalerInfor.Name}}</td>
                <td>{{item.statusName}}</td>
                <td>{{item.TotalPriceVND}}</td>
                <td>
                    <?php
                    if (Duser::KiemTraQuyen([Duser::admin, Duser::NhanVien, Duser::Superadmin])) {
                        ?>
                        <button class="btn btn-primary" ng-click="GetOrderDetail(item.CodeOrder)" data-toggle="modal"
                            data-target='#DonHangChiTiet'>Xem</button>
                        <?php
                    }
                    ?>
                </td>
            </tr>
        </table>
        <phan-trang1 pages-index="_DanhSachDonHang.indexPage" pages-number="_DanhSachDonHang.pageNumber"
            pages-total="_DanhSachDonHang.totalPage" pages-link="" pages-params='_DanhSachDonHang.Params'
            on-click="DanhSachAllDonHang(Params, pagesIndex, pagesNumber)"></phan-trang1>
        <div class="modal fade" id="DonHangChiTiet">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="donhang-chitiet"></div>
                    <div class="modal-footer">
                        <div class="form-group pull-left">
                            <!-- <button type="button" class="btn btn-success" ng-click="XacNhanDonHang(_OrderDetail.CodeOrder)">Đã Xác Minh <i class="fa  fa-check"></i></button>
                                <button type="button" class="btn btn-primary" ng-click="ShowChuyenNhanVienAction()">Chuyển Nhân Viên <i class="fa  fa-arrow-right"></i></button> -->
                            <a target="_blank" href="/cart/thanhcong/inphieu/{{_OrderDetail.CodeOrder}}"
                                class="btn btn-success">
                                In lại hóa đơn
                            </a>
                            <?php
                            if (Duser::KiemTraQuyen([Duser::admin, Duser::QuanLy, Duser::Superadmin])) {
                                ?>
                                <button type="button" class="btn btn-danger" ng-click="ShowLyDoAction()">Hủy Đơn Hàng <i
                                        class="fa  fa-times"></i></button>
                                <?php
                            }
                            if (Duser::KiemTraQuyen([Duser::admin, Duser::NhanVien, Duser::Superadmin])) {
                                ?>
                                <a ng-show="_OrderDetail.Status == '4'" target="_blank"
                                    href="/cart/vieworder/thanhtoan/{{_OrderDetail.CodeOrder}}"
                                    class="btn btn-success">Thanh Toán</a>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Thoát</button>
                                <?php
                            }
                            ?>
                        </div>
                    </div>
                    <div class="col-md-12" ng-show="ShowLyDo" style="margin-bottom: 15px;">
                        <div class="form-group">
                            <label for="">Lý Do</label>
                            <textarea type="text" class="form-control" ng-model="LyDo" name="name"
                                placeholder="Lý Do"></textarea>
                        </div>
                        <button type="button" class="btn pull-right btn-sm btn-success"
                            ng-click="HuyDonHang(LyDo, _OrderDetail.CodeOrder)">Xác Nhận</button>
                    </div>
                    <div class="col-md-12" ng-show="ShowChuyenNhanVien" style="margin-bottom: 15px;">
                        <div class="d-flex" ng-show="_NhanVien">
                            <div class="">
                                <h3>{{_NhanVien.Name}}</h3>
                                <p>{{_NhanVien.Username}}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="">Nhân Viên</label>
                            <input type="text" class="form-control" ng-model="nameNhanVien"
                                ng-change="TimKiemNhanVien(nameNhanVien)" name="name" placeholder="Tìm Nhân Viên">
                            <div>
                                <ul class="list-group">
                                    <li class="list-group-item" ng-repeat="item in _NhanViens.data">
                                        {{item.Name}} <button ng-click="ChonNhanVien(item)">Chọn</button>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <button ng-show="_NhanVien" type="button" class="btn pull-right btn-sm btn-success"
                            ng-click="ChuyenDonHang(_NhanVien.Username, _OrderDetail.CodeOrder)">Xác Nhận</button>
                    </div>
                    <div class="clearfix">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>