<?php
 
use Module\cart\Model\Order;

?>
<script src="/public/home/bachhoagiadinh/App.js?v=<?php echo 'public/home/bachhoagiadinh/App.js'; ?>" type="text/javascript"></script>
<?php
$order = new Order($_Param[0]);

if ($order->Status == Order::DaThuTien) {
?>
    <h3>Đã Thanh Toán</h3>
<?php
} else {
?>
    <div class="container" ng-controller="menuController" ng-init="GetOrderById('<?php echo $_Param[0]; ?>')">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Thanh toán</h3>
                    </div>
                    <div class="box-body">
                        <form action="" method="POST">
                            <div class="form-group">
                                <label for="">Nhập thẻ</label>
                                <input ng-model="maThe" required value="" type="password" style="font-size: 2em;padding: 30px;line-height: 30px;text-align: center;" id="MaThe" type="text" autofocus name="thanhToan[MaThe]" placeholder="Nhập mã thẻ ***" class="form-control">
                                <input value="<?php echo $_Param[0] ?>" type="hidden" type="hidden" name="thanhToan[MaDonHang]">
                            </div>
                            <button class="btn btn-success">Xác Nhận</button>
                        </form>
                        <table ng-show="_CartByOrder" style="margin-top: 20px;" class="table table-bordered table-responsive cart_summary">
                            <thead>
                                <tr style="background-color: gold;padding-bottom: 5px;padding-top: 5px;">
                                    <th class="">
                                        <h3 style="font-size: 16px;">
                                            <b>Danh sách Sản Phẩm</b>
                                        </h3>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="items  in _CartByOrder.OrderDetail">
                                    <td class="cart_description">
                                        <div class="d-flex giohang">
                                            <div class="" style="width: 100%;padding-right: 10px;">
                                                <h2 style="font-size: 16px;" class="product-name">
                                                    <b>{{items.Product.nameProduct}}</b>
                                                </h2>
                                                <small class="cart_ref">Id : #{{items.Product.Code}}</small><br>
                                                <p> <span ng-bind-html="items.PriceVND"></span></p>
                                            </div>
                                            <div class="qty" style="min-width: 76px;">
                                                <input class="inputcartnumber form-control input-sm" type="text" ng-value="items.Number">
                                            </div>
                                            <div class="hidden-sm hidden-xs" style="width: 120px;padding-left: 10px;">
                                                <strong ng-bind-html="ToHtml(items.ThanhTienVND)"></strong>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <p class="text-right">Tổng Tiền: <b ng-bind-html="_CartByOrder.TotalPriceVND"></b></p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php
}
?>