<div class="panel " style="margin-top: 40px;margin-bottom: 40px;" >
    <div class="panel-heading">
        <h2 class="text-center" ><span style="border-bottom: 2px solid #000;padding-bottom: 5px;" ><?php echo $cat->catName; ?></span></h2>
    </div>
    <div class="container">
        <ul class="product-list owl-carousel" data-dots="false" data-loop="true" data-nav = "true" data-margin = "30"
            data-autoplayTimeout="1000" data-autoplayHoverPause = "true"
            data-responsive='{"0":{"items":1},"600":{"items":3},"1000":{"items":5}}'>
            <li>
                <div class="left-block">
                    <a href="#">
                        <img class="img-responsive" alt="product" src="/public/home/assets/data/bs1.jpg" />
                    </a>
                    <div class="quick-view">
                        <a title="Add to my wishlist" class="heart" href="#"></a>
                        <a title="Add to compare" class="compare" href="#"></a>
                        <a title="Quick view" class="search" href="#"></a>
                    </div>
                    <div class="add-to-cart">
                        <a title="Add to Cart" href="#">Add to Cart</a>
                    </div>
                    <div class="group-price">
                        <span class="product-new">NEW</span>
                        <span class="product-sale">Sale</span>
                    </div>
                </div>
                <div class="right-block">
                    <h5 class="product-name"><a href="#">Sexy Lady</a></h5>
                    <div class="content_price">
                        <span class="price product-price">$38,95</span>
                        <span class="price old-price">$52,00</span>
                    </div>
                    <div class="product-star">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-half-o"></i>
                    </div>
                </div>
            </li>
            <li>
                <div class="left-block">
                    <a href="#"><img class="img-responsive" alt="product" src="/public/home/assets/data/bs2.jpg" /></a>
                    <div class="quick-view">
                        <a title="Add to my wishlist" class="heart" href="#"></a>
                        <a title="Add to compare" class="compare" href="#"></a>
                        <a title="Quick view" class="search" href="#"></a>
                    </div>
                    <div class="add-to-cart">
                        <a title="Add to Cart" href="#">Add to Cart</a>
                    </div>
                </div>
                <div class="right-block">
                    <h5 class="product-name"><a href="#">Perfect Dress</a></h5>
                    <div class="content_price">
                        <span class="price product-price">$38,95</span>
                        <span class="price old-price">$52,00</span>
                    </div>
                    <div class="product-star">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-half-o"></i>
                    </div>
                </div>
            </li>
            <li>
                <div class="left-block">
                    <a href="#"><img class="img-responsive" alt="product" src="/public/home/assets/data/bs3.jpg" /></a>
                    <div class="quick-view">
                        <a title="Add to my wishlist" class="heart" href="#"></a>
                        <a title="Add to compare" class="compare" href="#"></a>
                        <a title="Quick view" class="search" href="#"></a>
                    </div>
                    <div class="add-to-cart">
                        <a title="Add to Cart" href="#">Add to Cart</a>
                    </div>
                </div>
                <div class="group-price">
                    <span class="product-new">NEW</span>
                </div>
                <div class="right-block">
                    <h5 class="product-name"><a href="#">Fresh Summer</a></h5>
                    <div class="content_price">
                        <span class="price product-price">$38,95</span>
                        <span class="price old-price">$52,00</span>
                    </div>
                    <div class="product-star">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-half-o"></i>
                    </div>
                </div>
            </li>
            <li>
                <div class="left-block">
                    <a href="#"><img class="img-responsive" alt="product" src="/public/home/assets/data/bs4.jpg" /></a>
                    <div class="quick-view">
                        <a title="Add to my wishlist" class="heart" href="#"></a>
                        <a title="Add to compare" class="compare" href="#"></a>
                        <a title="Quick view" class="search" href="#"></a>
                    </div>
                    <div class="add-to-cart">
                        <a title="Add to Cart" href="#">Add to Cart</a>
                    </div>
                </div>
                <div class="right-block">
                    <h5 class="product-name"><a href="#">Flowers Dress</a></h5>
                    <div class="content_price">
                        <span class="price product-price">$38,95</span>
                        <span class="price old-price">$52,00</span>
                    </div>
                    <div class="product-star">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-half-o"></i>
                    </div>
                </div>
            </li>
            <li>
                <div class="left-block">
                    <a href="#">
                        <img class="img-responsive" alt="product" src="/public/home/assets/data/bs1.jpg" />
                    </a>
                    <div class="quick-view">
                        <a title="Add to my wishlist" class="heart" href="#"></a>
                        <a title="Add to compare" class="compare" href="#"></a>
                        <a title="Quick view" class="search" href="#"></a>
                    </div>
                    <div class="add-to-cart">
                        <a title="Add to Cart" href="#">Add to Cart</a>
                    </div>
                    <div class="group-price">
                        <span class="product-new">NEW</span>
                        <span class="product-sale">Sale</span>
                    </div>
                </div>
                <div class="right-block">
                    <h5 class="product-name"><a href="#">Sexy Lady</a></h5>
                    <div class="content_price">
                        <span class="price product-price">$38,95</span>
                        <span class="price old-price">$52,00</span>
                    </div>
                    <div class="product-star">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-half-o"></i>
                    </div>
                </div>
            </li>
            <li>
                <div class="left-block">
                    <a href="#"><img class="img-responsive" alt="product" src="/public/home/assets/data/bs2.jpg" /></a>
                    <div class="quick-view">
                        <a title="Add to my wishlist" class="heart" href="#"></a>
                        <a title="Add to compare" class="compare" href="#"></a>
                        <a title="Quick view" class="search" href="#"></a>
                    </div>
                    <div class="add-to-cart">
                        <a title="Add to Cart" href="#">Add to Cart</a>
                    </div>
                </div>
                <div class="right-block">
                    <h5 class="product-name"><a href="#">Perfect Dress</a></h5>
                    <div class="content_price">
                        <span class="price product-price">$38,95</span>
                        <span class="price old-price">$52,00</span>
                    </div>
                    <div class="product-star">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-half-o"></i>
                    </div>
                </div>
            </li>
            <li>
                <div class="left-block">
                    <a href="#"><img class="img-responsive" alt="product" src="/public/home/assets/data/bs3.jpg" /></a>
                    <div class="quick-view">
                        <a title="Add to my wishlist" class="heart" href="#"></a>
                        <a title="Add to compare" class="compare" href="#"></a>
                        <a title="Quick view" class="search" href="#"></a>
                    </div>
                    <div class="add-to-cart">
                        <a title="Add to Cart" href="#">Add to Cart</a>
                    </div>
                </div>
                <div class="group-price">
                    <span class="product-new">NEW</span>
                </div>
                <div class="right-block">
                    <h5 class="product-name"><a href="#">Fresh Summer</a></h5>
                    <div class="content_price">
                        <span class="price product-price">$38,95</span>
                        <span class="price old-price">$52,00</span>
                    </div>
                    <div class="product-star">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-half-o"></i>
                    </div>
                </div>
            </li>
            <li>
                <div class="left-block">
                    <a href="#"><img class="img-responsive" alt="product" src="/public/home/assets/data/bs4.jpg" /></a>
                    <div class="quick-view">
                        <a title="Add to my wishlist" class="heart" href="#"></a>
                        <a title="Add to compare" class="compare" href="#"></a>
                        <a title="Quick view" class="search" href="#"></a>
                    </div>
                    <div class="add-to-cart">
                        <a title="Add to Cart" href="#">Add to Cart</a>
                    </div>
                </div>
                <div class="right-block">
                    <h5 class="product-name"><a href="#">Flowers Dress</a></h5>
                    <div class="content_price">
                        <span class="price product-price">$38,95</span>
                        <span class="price old-price">$52,00</span>
                    </div>
                    <div class="product-star">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>