<?php
$bk = new theme\backend\backend();
$a = new Model_Adapter();
$sidebartoggle = $_COOKIE["sidebar-toggle"] ?? "";
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Quản trị</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?php
    $bk->head();
    ?>
    <script src="/public/partials/loaderpartials/backend/backendconfig.js" type="text/javascript"></script>

</head> 
<body  class="hold-transition <?php echo $sidebartoggle ?> fixed skin-blue-light  " ng-cloak="TRUE" ng-controller="appController" ng-app="rootApp">
    <div class="wrapper">
        <?php
        $bk->Menu();
        ?>
        <div class="content-wrapper">
            <?php
            $bk->Breadcrumb();
            ?>
            <section class="content">
                <?php include $Content; ?>
            </section>

        </div>
    </div>
    <?php
    $bk->js();
    ?>
</body>

</html>