<div class="container" >
    <div class="col-md-6" ng-controller="categorydetailController">
        <form action="/mcategory/edit/" method="POST" enctype="multipart/form-data">
            <div class="box">
                <div class="box-body">
                    <div class="form-group">
                        <label>Mã Danh Mục</label>
                        <input type="text" name="Code" class="form-control" ng-model="_CategoryDetail.Code"
                            placeholder="Mã Danh Mục">
                    </div>
                    <div class="form-group">
                        <label>Tên Danh Mục</label>
                        <input type="hidden" name="catID" value="{{_CategoryDetail.catID}}">
                        <input type="text" required="required" class="form-control" ng-model="_CategoryDetail.catName"
                            name="catName" placeholder="Tên Danh Mục">
                    </div>
                    <div class="form-group">
                        <label>Tên Không Đấu</label>
                        <input type="text" class="form-control" ng-model="_CategoryDetail.Path" readonly="readonly"
                            placeholder="Tên Không Dấu">
                    </div>
                    <div class="form-group">
                        <label>Đường Dẫn</label>
                        <input type="text" class="form-control" ng-model="_CategoryDetail.Link" readonly="readonly"
                            placeholder="Đường Dẫn">
                    </div>
                    <div class="form-group">
                        <label>Đường Dẫn</label>
                        <input type="text" class="form-control" ng-model="_CategoryDetail.Serial" name="Serial"
                            placeholder="Thứ Tự">
                    </div>
                    <div class="form-group">
                        <label>Danh Mục Cấp Trên</label>
                        <select ng-model="_CategoryDetail.parentCatID" name="parentCatID" class="form-control select2">
                            <option value="0">Là Cấp Cha</option>
                            <option ng-repeat="item in ListCategory" value="{{item.catID}}">{{item.catName}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Ghi Chú</label>
                        <textarea name="Note" class="form-control" ng-model="_CategoryDetail.Note"
                            placeholder="Tên Danh Mục"></textarea>
                    </div>
                    <div class="form-group">
                        <label>
                            Ẩn Hiện
                            <input type="checkbox" name="Public" ng-checked="_CategoryDetail.Public == 1"
                                ng-model="_CategoryDetail.Public">
                        </label>
                    </div>
    
                </div>
                <div class="box-footer">
                    <div class="text-right">
                        <a class="btn btn-primary pull-left" href='/mcategory/'>Quay Lại</a>
                        <button class="btn btn-default" type="reset"> reset</button>
                        <button class="btn btn-success" type="submit" name="SuaDanhMuc"> Sửa</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>