<div class="row " ng-controller="listcategorysController">
    <section class="col-md-12" >
        <div class="box box-solid ">
            <div class="box-header ">
                <i class="fa fa-book"></i>
                <h3 class="box-title">Danh Mục Sản Phẩm ({{ListCategory.length}})</h3> 
                <div class="box-tools">
                    <button class="btn btn-primary" ng-click="formcategoryInit(0, false)" data-toggle="modal" data-target='#modalThem'>Thêm</button>
                </div>
            </div>
            <div class="box-body  ">
                <div class=""  >
                    <div class="col-md-12 " >
                        <div class="modal fade" id="modalThem">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h3 class="modal-title">Danh Mục </h3>
                                    </div>
                                    <div class="modal-body">
                                        <div class="box-body bakco-formcategory" ng-init="formcategoryInit(_CategoryDetail.catID, true)" >
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <table class="table " >
                            <tr>
                                <th><input class="form-control" ng-model="Timkiem.Code" placeholder="Mã Danh Mục" ></th>
                                <th><input class="form-control" ng-model="Timkiem.catName" placeholder="Tên Danh Mục" ></th>
                                <th>
                                    <select ng-model="Timkiem.parentCatID" class="form-control select2" >
                                        <option value="" >Tất cả</option>
                                        <option ng-repeat="item in _ProductCategory" value="{{item.catID}}" >{{item.catName}}</option>
                                    </select>
                                </th>
                            </tr>
                        </table>
                        <div class="clearfix" ></div>
                        <div class="  table-responsive"   >
                            <table class="table table-bordered table-hover"  >
                                <thead>
                                    <tr class="bg-blue" >
                                        <th>STT</th>
                                        <th>Mã Danh Mục</th>
                                        <th>Tên Danh Mục</th>
                                        <th>Tên Danh Mục Cha</th>
                                        <th>Số Thứ Tự</th>
                                        <th>Ẩn Hiển</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody  >
                                    <tr ng-repeat="item in _ProductCategory| filter : Timkiem" >
                                        <td>{{$index + 1}}
                                        </td>
                                        <td>
                                            <span >{{item.Code}}</span>
                                        </td>
                                        <td><span  ><b>{{item.catName}}</b></span>
                                        </td>
                                        <td>
                                            <span ng-show="item.parentCatID != 0" >{{showNameCategory(item.parentCatID)}}</span>
                                            <span ng-show="item.parentCatID == 0" >{{showNameCategory(item.parentCatID)}}</span>
                                        </td>

                                        <td>{{item.Serial}}</td>
                                        <td>{{item.Public==1?"Hiện":"Ẩn"}}</td>
                                        <td> 
                                            <a class="btn btn-primary" href="/mcategory/edit/{{item.catID}}" >Sửa</a>

                                            <button class="btn btn-primary btn-xs" data-toggle="modal" data-target='#modalThem' type="button" ng-click="selectCategory(item.catID)" >Chọn</button>
                                        </td>
                                    </tr>
                                </tbody> 

                            </table>
                        </div>
                    </div>
                </div>
            </div><!-- /.box-body -->
        </div>
    </section>
</div>